apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microosd.fullname" . }}-ceph-keyring
  labels:
    {{- include "microosd.labels" . | nindent 4 }}
stringData:
  keyring: |
{{ .Values.keyring | indent 4 }}
