apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "microosd.fullname" . }}
  labels:
    {{- include "microosd.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "microosd.fullname" . }}
  selector:
    matchLabels:
      {{- include "microosd.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "microosd.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      {{- with .Values.cephConfRootVolumeSpec }}
      - name: ceph-conf-root
        {{- toYaml . | nindent 8 }}
      {{- end }}
      - name: ceph-keyring
        secret:
          secretName: {{ include "microosd.fullname" . }}-ceph-keyring
      initContainers:
      - name: copy-keyring
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: ceph-keyring
          mountPath: /keyring
          subPath: keyring
        - name: ceph-conf-root
          mountPath: /etc/ceph
        command:
        - /bin/bash
        - -c
        - |
          set -xe
          cp /keyring /etc/ceph
          chmod 0600 /etc/ceph/keyring
      containers:
      - name: microosd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # command: ["/bin/bash", "-c", "while true; do sleep 1; done"]
        # killall -9 ceph-{mon,osd,mgr,mds} radosgw ; rm -rf $(ls /etc/ceph/ | grep -v -e keyring -e ceph.conf) -v # CLEAR
        # ceph auth get-or-create mgr.$name mon 'allow profile mgr' osd 'allow *' mds 'allow *'
        securityContext:
          capabilities:
            add: [ALL]
          privileged: true
        env:
        # - name: CEPH_ADDR
        #   value: {{ include "microosd.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        - name: CEPH_FEATURESET
          value: 'mon mgr osd mds selftest'
        - name: CEPH_AUTH_METHOD
          value: {{ .Values.cephAuthMethod }}
        - name: CEPH_CONF_ROOT
          value: /etc/ceph
        {{- if .Values.cephConfRootVolumeSpec }}
        volumeMounts:
        - name: ceph-conf-root
          mountPath: /etc/ceph
        {{- end }}
        # startupProbe:
        #   exec:
        #     command:
        #       - stat
        #       - /etc/ceph/.ready
        #   initialDelaySeconds: 50
        #   periodSeconds: 1
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
