# Default values for microosd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cephConfRootVolumeSpec:
  emptyDir: {}
  # hostPath:
  #   path: /tmp/microosd-ceph-conf
  #   type: DirectoryOrCreate

# https://docs.ceph.com/en/latest/rados/configuration/auth-config-ref/#enablement
# Default auth method is "cephx".
# "none" disable auth altogether.
cephAuthMethod: none

keyring: |
  [mon.Z]
  	key = AQCZF99miT2gGRAA1lt7FYK1rsFUUNTdnu3Yyw==
  	caps mds = "allow *"
  	caps mgr = "allow *"
  	caps mon = "allow *"
  	caps osd = "allow *"
  [osd.0]
  	key = AQCgF99mv42/HxAAApUko+w0IY09RXgk8KTT3Q==
  	caps mds = "allow *"
  	caps mgr = "allow *"
  	caps mon = "allow *"
  	caps osd = "allow *"
  [client.admin]
  	key = AQDtEt9mjOVWLxAALFsRy42v9O28FrPhfBYCrg==
  	caps mds = "allow *"
  	caps mgr = "allow *"
  	caps mon = "allow *"
  	caps osd = "allow *"
  [mgr.x]
  	key = AQColOFmo83PLBAAr1lpk2ZBGkyri/9PZnbMJg==
  	caps mds = "allow *"
  	caps mon = "allow profile mgr"
  	caps osd = "allow *"
image:
  repository: rvasek/micro-osd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

resources:
  limits:
    cpu: 100m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 3Gi

nodeSelector:
  kubernetes.io/hostname: ik8s

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""
