# Default values for microosd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cephConfRootVolumeSpec:
  emptyDir: {}
  # hostPath:
  #   path: /tmp/microosd-ceph-conf
  #   type: DirectoryOrCreate

extraKeyrings:
  - name: client.admin
    values:
      "key": "AQCAVwpi/9BDMxAAnXEqoz46veFB2AFW45sEGQ=="
      "caps mds": '"allow *"'
      "caps mgr": '"allow *"'
      "caps mon": '"allow *"'
      "caps osd": '"allow *"'

image:
  repository: registry.cern.ch/rvasek/micro-osd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

resources:
  limits:
    cpu: 100m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 3Gi

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""
